export const POPULAR_SET_SELECTED_LANGUAGE = 'POPULAR_SET_SELECTED_LANGUAGE';
export const POPULAR_SET_LOADING = 'POPULAR_SET_LOADING';
export const POPULAR_SET_REPOS = 'POPULAR_SET_REPOS';
export const POPULAR_SET_ERRORS = 'POPULAR_SET_ERRORS';